---
  el:
    hosts:
      centos7:
        ansible_connection: docker
  deb:
    hosts:
      debian:
        ansible_connection: docker
  loc:
    hosts:
      localhost:
        ansible_connection: local